### ISSUE TITLE
setup binsegRcpp fork with PR

### ISSUE THREAD

**Issue by tdhock** [Anirban166/Autocomment-plot-GA#21]
like this https://github.com/SiyaoIsHiding/binsegRcpp/pull/4 but hopefully with a nice plot comment

**Comment by Anirban166** [comment]
Done! (Please check the [PR](https://github.com/Anirban166/binsegRcpp/pull/1) I made on my fork of binsegRcpp)

**Comment by tdhock** [comment]
almost, see https://github.com/Anirban166/binsegRcpp/pull/1#issuecomment-1986076421
